substitutions:
  name: 'ArlecTestBulb'
  device: 'arlectestbulb'
  reboot_timeout: 1h
  update_interval: 1min
  
esphome:
  name: ${device}
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "arlectestbulb Fallback Hotspot"
    password: !secret ap_pass

# Enable logging
logger:
  level: DEBUG
  #level: VERY_VERBOSE

ota:

api:

output:
  - platform: esp8266_pwm
    id: output_led
    pin: D4
    min_power: 0.50


light:
  - platform: monochromatic
    name: 'Test_LED'
    output: output_led
    default_transition_length: 0s
    gamma_correct: 0.0