esphome:
  name: oliverac
  platform: ESP8266
  board: d1_mini
  includes: 
    - panasonic_ir.h
  libraries:
    - IRremoteESP8266

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "oliverac Fallback Hotspot"
    password: !secret ap_pass

# Enable logging
logger:

ota:

api:

climate:
- platform: custom
  lambda: |-
    auto my_panasonic = new PanasonicAC();
    App.register_component(my_panasonic);
    return {my_panasonic};

  climates:
    - name: "Oliver's AC"

    #implement slider for vertical Swing
    #and quiet+powerful buttons