esphome:
  name: oliverac
  platform: ESP32
  board: wemos_d1_mini32

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "oliverac Fallback Hotspot"
    password: !secret ap_pass

# Enable logging
logger:
    # level: VERBOSE

ota:

api:

external_components:
  - source:
      type: git
      url: https://github.com/WeekendWarrior1/esphome
      ref: final_ac
    components: [ panasonic ]

# e131:
  # method: unicast

wled:

light:
  - platform: neopixelbus
    type: RGBW
    pin: GPIO17
    variant: SK6812
    num_leds: 14
    name: "Oliver's AC LED Strip"
    effects:
      # - e131:
      #     universe: 1
      #     channels: RGB
      - addressable_rainbow:
          width: 18
      - wled:

# remote_receiver:
#   id: rcvr
#   pin:
#     number: GPIO23
#     inverted: True
#     mode: INPUT_PULLUP
#   tolerance: 55%

remote_transmitter:
  pin:
    number: GPIO16
    inverted: True
  carrier_duty_percent: 100%

climate:
  - platform: panasonic
    name: "Oliver's AC"
    # receiver_id: rcvr
    # supports_vertical_swing: true
    conf_supports_vertical_swing: true

esp32_ble_tracker:

sensor:
  - platform: xiaomi_lywsd03mmc
    mac_address: "A4:C1:38:D6:F5:5D"
    bindkey: "8b672dd2ddfb53abbf4b419603242f54"
    temperature:
      name: "Oliver's Room Temperature"
    humidity:
      name: "Oliver's Room Humidity"
    battery_level:
      name: "LYWSD03MMC Battery Level"