esphome:
  name: dylanac
  platform: ESP32
  board: wemos_d1_mini32

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "dylanac Fallback Hotspot"
    password: !secret ap_pass

# Enable logging
logger:
    # level: VERBOSE

ota:

api:

e131:
  method: unicast

light:
  - platform: neopixelbus
    type: RGBW
    pin: GPIO17
    variant: SK6812
    num_leds: 14
    name: "Dylan's AC LED Strip"
    effects:
      - e131:
          universe: 1
          channels: RGB
      - addressable_rainbow:
          width: 18

# remote_receiver:
#   id: rcvr
#   pin:
#     number: GPIO23
#     inverted: True
#     mode: INPUT_PULLUP
#   tolerance: 55%

remote_transmitter:
  pin:
    number: GPIO16
    inverted: True
  carrier_duty_percent: 100%

climate:
  - platform: panasonic
    name: "Dylan's AC"
    # receiver_id: rcvr
    supports_vertical_swing: true